apiVersion: apps/v1
kind: Deployment
metadata:
  name: workd-coin-converter
  labels:
    app: workd-coin-converter
    env: __ENV__
spec:
  selector:
    matchLabels:
      app: workd-coin-converter
  template:
    metadata:
      labels:
        app: workd-coin-converter
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com

      containers:
        - name: workd-coin-converter
          image: __DOCKER_IMAGE__
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
              cpu: 250m
            requests:
              memory: 256Mi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: workd-coin-converter-configmap
            - secretRef:
                name: workd-coin-converter-secret
          ports:
            - containerPort: __PORT__
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: workd-coin-converter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workd-coin-converter
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80
