apiVersion: v1
kind: Service
metadata:
  name: workd-coin-converter-svc
spec:
  ports:
    - port: __PORT__
      targetPort: __PORT__
  selector:
    app: workd-coin-converter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workd-coin-converter-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: __ISSUER__
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: __DNS__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workd-coin-converter-svc
                port:
                  number: __PORT__
  tls:
    - hosts:
        - __DNS__
      secretName: wcc-cert
